//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculateTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class Divisions
    {
        public Divisions()
        {
            this.games = new HashSet<games>();
            this.Tables = new HashSet<Tables>();
            this.TeamSeasonDivision = new HashSet<TeamSeasonDivision>();
        }
    
        public long DivisionId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<games> games { get; set; }
        public virtual ICollection<Tables> Tables { get; set; }
        public virtual ICollection<TeamSeasonDivision> TeamSeasonDivision { get; set; }
    }
}
