//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculateTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableLines
    {
        public long TableLineId { get; set; }
        public long TableId { get; set; }
        public long TeamId { get; set; }
        public int Points { get; set; }
        public int Bonus { get; set; }
        public int TotalPoints { get; set; }
        public int Games { get; set; }
        public int Won { get; set; }
        public int Draw { get; set; }
        public int Lost { get; set; }
        public int Forfait { get; set; }
        public int PositivePoints { get; set; }
        public int NegativePoints { get; set; }
        public int RedCards { get; set; }
    }
}
