//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculateTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teams
    {
        public Teams()
        {
            this.games = new HashSet<games>();
            this.games1 = new HashSet<games>();
            this.TeamSeasonDivision = new HashSet<TeamSeasonDivision>();
        }
    
        public long TeamId { get; set; }
        public string Team { get; set; }
    
        public virtual ICollection<games> games { get; set; }
        public virtual ICollection<games> games1 { get; set; }
        public virtual ICollection<TeamSeasonDivision> TeamSeasonDivision { get; set; }
    }
}
