//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkerRole1
{
    using System;
    using System.Collections.Generic;
    
    public partial class games
    {
        public long GameId { get; set; }
        public long SeasonId { get; set; }
        public long Divisionid { get; set; }
        public string GameNumber { get; set; }
        public long Team1Id { get; set; }
        public Nullable<int> Team1Score { get; set; }
        public Nullable<int> Team1Tries { get; set; }
        public long Team2Id { get; set; }
        public Nullable<int> Team2Score { get; set; }
        public Nullable<int> Team2Tries { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Divisions Divisions { get; set; }
        public virtual Seasons Seasons { get; set; }
        public virtual Teams Teams { get; set; }
        public virtual Teams Teams1 { get; set; }
    }
}
