//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkerRole1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seasons
    {
        public Seasons()
        {
            this.games = new HashSet<games>();
            this.TeamSeasonDivision = new HashSet<TeamSeasonDivision>();
        }
    
        public long SeasonId { get; set; }
        public string Description { get; set; }
        public int StartYear { get; set; }
        public int EndYear { get; set; }
    
        public virtual ICollection<games> games { get; set; }
        public virtual ICollection<TeamSeasonDivision> TeamSeasonDivision { get; set; }
    }
}
