//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkerRole1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamSeasonDivision
    {
        public long TeamId { get; set; }
        public long DivisionId { get; set; }
        public long SeasonId { get; set; }
        public long Id { get; set; }
    
        public virtual Divisions Divisions { get; set; }
        public virtual Seasons Seasons { get; set; }
        public virtual Teams Teams { get; set; }
    }
}
